blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/DineshPriyanthaGH/cloudchat-realtime-chat-application/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/DineshPriyanthaGH/cloudchat-realtime-chat-application#readme
    about: Read the project documentation
  - name: 🎥 Demo Video
    url: https://drive.google.com/file/d/14_VyMQ1rAvhYhJKivIGPte9jzyfL6FCk/view?usp=drive_link
    about: Watch the CloudChat demo video
