name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: cloudchat/package-lock.json
        
    - name: Install dependencies
      run: |
        cd cloudchat
        npm ci
        
    - name: Run ESLint
      run: |
        cd cloudchat
        npm run lint
        
    - name: Type check
      run: |
        cd cloudchat
        npx tsc --noEmit
        
    - name: Build project
      run: |
        cd cloudchat
        npm run build
        
    - name: Run tests (when available)
      run: |
        cd cloudchat
        # npm test (uncomment when tests are added)
        echo "Tests will be added in future versions"

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: cloudchat/package-lock.json
        
    - name: Install dependencies
      run: |
        cd cloudchat
        npm ci
        
    - name: Build for production
      run: |
        cd cloudchat
        npm run build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: cloudchat/dist/
        retention-days: 30
